[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Hafıza sınırını 3 MB programa genişleten konfigürasyon
board_build.partitions = huge_app.csv

lib_deps = 
    lovyan03/LovyanGFX @ ^1.1.12